### ISSUE TITLE
Allow unit tests to work if the tested model's schema doesn't exist

### ISSUE THREAD

**Issue by lkell** [mjirv/dbt-datamocktool#12]
### Describe the feature
Currently unit tests work if the tested model's schema already exists. It would be helpful to extend this to work even if the model's schema doesn't exist so that unit tests can be run in "empty" databases. This would be beneficial for things like data warehouse testing pipelines that involve spinning up an isolated test database to validate model transformation code.

### Describe alternatives you've considered
The test pipeline mentioned above could be made to work by first adding a subset of source data to the isolated test database and then running the models once. But this would add extra time and complexity to the pipeline that could potentially be mitigated.

### Additional context
Currently the tested model's schema needs to exist because the `mock_model_relation` temp table is created in the same schema. I'm not exactly sure if the resulting "schema does not exist" error applies to databases other than MSSQL but I can do further investigation. 

To prevent the error from happening, one option is make the temp table's schema the same as one of the mock input seed's schemas, because we know that the seed schemas must already exist at test time. This could be done with the following code:

```
{% set temp_schema = input_mapping.values() | list | first | attr("schema") %}
{% set mock_model_relation = mock_model_relation.incorporate(path={"schema": temp_schema}) %}
```

However, as mentioned by @mjirv, this modification would not work in situations where the input replacement is a macro or CTE.

### Who will this benefit?
CI/CD pipelines might have an automated testing component that involves spinning up a lightweight database instance, seeding the mock input and expected output tables, and then running unit tests. These types of pipelines would benefit from the requested feature.

### Are you interested in contributing this feature?
Yes, I am happy to contribute.

**Comment by mjirv** [comment]
Some ways to solve:
1. We could just call some sort of “create schema if not exists” statement before creating the temp table 
2. We could use something like `dbt_utils._is_relation` to check if the input is a relation, and have different logic depending on whether it is or isn’t.

One other thing is I’m pretty sure the temp table gets created in a separate schema on at least Redshift and Postgres, so I wonder if this is only an MSSQL problem. Will try and look into it more tomorrow.

**Comment by lkell** [comment]
The [create_schema](https://docs.getdbt.com/reference/dbt-jinja-functions/adapter#create_schema) docs say "If the target schema already exists, then this method is a no-op." So for option 1, we may be able to do something simple like the following, without needing to check for existence first:

`{% do adapter.create_schema(api.Relation.create(schema=model.schema)) %}`

I also suspect you are right about this being an MSSQL-specific problem...

**Comment by mjirv** [comment]
Hi @lkell. Sorry I missed your last comment. That line of code seems to work! I added a branch called `feature-allow_nonexistent_schema`. Would you mind testing if it works on SQL Server when you have a chance? Or maybe you already have. Thanks!

**Comment by lkell** [comment]
No problem @mjirv! I will try to test the latest and let you know tomorrow if it works out.

**Comment by lkell** [comment]
@mjirv sorry I got to testing it a bit later than planned. I'm currently getting the following error with `dbt deps`:

Encountered an error:
Found duplicate project "dbt_utils". This occurs when a dependency has the same project name as some other dependency.

**Comment by mjirv** [comment]
@lkell my bad, I forgot you needed a version that uses `fishtown-analytics/dbt_utils`. You can use the branch `feature-allow_nonexistent_schema_fishtown` now!

**Comment by lkell** [comment]
@mjirv It's working now as expected. Thank you for the update!
