### ISSUE TITLE
Option to choose which columns are used for the compare

### ISSUE THREAD

**Issue by chaimt** [mjirv/dbt-datamocktool#29]
### Describe the feature
I would like to specify which columns to compare the result and expected table. 
We will be generating the data, and only care about some of the columns

### Describe alternatives you've considered
changin the code

### Who will this benefit?
big tables, and test is only on some of the columns

### Are you interested in contributing this feature?
yes

**Comment by chaimt** [comment]
https://github.com/mjirv/dbt-datamocktool/pull/30

**Comment by mjirv** [comment]
Solved by #30
