### ISSUE TITLE
run unit tests independent from dbt test

### ISSUE THREAD

**Issue by b0lle** [mjirv/dbt-datamocktool#33]
### Describe the feature
As a software engineer I would like to unit test my Macros/UDFs/SQL Models, so that I can be confident that they work correctly. 
I want to unit tests before any dbt processing, so that I dont need to clean my database if something went wrong.
I do not want to run dbt test (which also can be a data test like source_freshness) at the same time, because data can be outdated at this point.

### Describe alternatives you've considered
Run tests provided by this package with
`dbt test --unit-test`
in a 'standalone' mode.
When you call
`dbt test`
they should be included.

With this feature I can run a Seequence like
`dbt seed`
`dbt test --unit-test --> I can be confident that macros work well`
`dbt run --> prozessing`
`dbt test --> data tests`

### Who will this benefit?
Everyone who want to get confident that his code works correctly before dbt runs any transformations.

### Are you interested in contributing this feature?
I need to clearify this

**Comment by mjirv** [comment]
Good idea. I think I figured out how to do this with selectors at one point. Let me check!

**Comment by mjirv** [comment]
Yes, you can do something like `dbt test --models test_name:unit_test`  or `dbt test --models test_name:dbt_datamocktool.unit_test`

Let me know if one of those works!

**Comment by b0lle** [comment]
Am I right that I need to specify all single test models in this selector?
So for two testcases I need to write:
`dbt test --models test_name1:unit_test test_name2:unit_test` 

Do you know a solution to run them all at once?
Like: `dbt test --models *:unit_test`

**Comment by mjirv** [comment]
@b0lle ah, sorry I was unclear. `test_name` isn't a variable--it's a selector that tells dbt to run tests with the name "unit_test". Just copy/paste in `dbt test --select test_name:unit_test` without changing anything and it should work!

Let me know if that solves it.

**Comment by b0lle** [comment]
oh great! Thank you very much for your great support!
