### ISSUE TITLE
Support for incremental models

### ISSUE THREAD

**Issue by mjirv** [mjirv/dbt-datamocktool#40]
### Describe the feature
Right now, datamocktool has no special handling for incremental models. While you _can_ run a unit test on an incremental model, I am not sure what will happen (i.e. whether it will run on the initial step or the incremental step).

We should support running on incremental models - presumably against the incremental and non-incremental steps separately.

A good UX would be that the user can:
1. add 2 mock data sets for an incremental model: the initial and the incremental
2. add 2 expected outputs (the initial and the final)
3. datamocktool will automatically check that both steps succeed

### Describe alternatives you've considered
- You can probably test just the initial step right now, though I am not totally sure

### Who will this benefit?
- Multiple people have mentioned wanting this, either in the context of datamocktool or more generally

### Are you interested in contributing this feature?
I plan to, but would love if someone else would like to as well!

**Comment by mkkuba** [comment]
What we have done is use a variable named `force_incremental`.

In our models, instead of `{% if is_incremental() %}`, we have `{% if is_incremental() or var('force_incremental') %}`

We have set up our tests to either test the full refresh:
```
dbt test --select tag:test-refresh
```

Or run the incremental test:
```
dbt test --select tag:test-incremental --vars 'force_incremental: true'
```

**Comment by mjirv** [comment]
@mkkuba genuis! I love it.

Are there any issues with this approach or does it work well for you?

**Comment by mkkuba** [comment]
> @mkkuba genuis! I love it.
> 
> Are there any issues with this approach or does it work well for you?

@mjirv thank you!  This has worked well for us so far.  Our usage with `dbt` is still just beginning, however, so we only have a few models using it.

**Comment by mkkuba** [comment]
> Hi! I tried out your approach @mkkuba but i cant get it to work. I get an error in the incremental code when i try to do a `(select max(date) from {{this}}) ` which evaluates to a dataset which does not exist -- it is the same name that of my dataset but with a suffix of "_dbt_test__audit"
> 
> `404 Not found: Dataset myproject:mydataset_dbt_test__audit was not found in location europe-north1`
> 
> I like the approach of testing like this but the two tests "test-refresh" and "test-incremental" will not be related will they? I would need a test to test the incremental logic, not only compiling and running the code on an empty table: test input run 1 -> expected run 1 . Test input run 2 (adds to run 1, incremental test) -> expected run 2

Hi @pettersoderlund , thanks for trying out the approach.  If your incremental update makes use of `{{ this }}`, you will have to add `{{ this }}` in the `input_mapping` section of the unit test, and provide seed data for that.  For our incremental tests, we have 3 seed tables usually: `table_input`, `table_existing`, and `table_expected`.  `{{ this }}` would be mapped to `table_existing`.

To your question, the two tests are basically independent and the incremental test does not necessarily "build" on the results of the other.  I suppose it might be possible to write the tests in such a way that some of the data could be re-used, but in our case we keep them separate.

**Comment by pettersoderlund** [comment]
Thank you for feedback @mkkuba ! 

I am currently trying to implement a function in data mocktool. I might ask for some feedback @mjirv :) I had some discussions with a colleague though and wouldn't the most straightforward unit test for an incremental model be to specify the current state of the incremental table instead of specify two mock data sets for input? This would very much mimic the style @mkkuba is trying out but I would like not having to use the tagging system/variable system since it would complicate CI/CD etc.

**Comment by mjirv** [comment]
@pettersoderlund yep, I think you're right about that. Let me know if there's anything you want me to take a look at!

**Comment by santicapchase** [comment]
> What we have done is use a variable named `force_incremental`.
> 
> In our models, instead of `{% if is_incremental() %}`, we have `{% if is_incremental() or var('force_incremental') %}`
> 
> We have set up our tests to either test the full refresh:
> 
> ```
> dbt test --select tag:test-refresh
> ```
> 
> Or run the incremental test:
> 
> ```
> dbt test --select tag:test-incremental --vars 'force_incremental: true'
> ```

Great approach, @mkkuba !

Just a question here...How are you adding the variable in the `yml` file? You need that variable to be defined in order for the incremental test to work properly when running `dbt build`, for example.

**Comment by pettersoderlund** [comment]
> 

hey @mjirv  :) 
I have made an attempt in https://github.com/mjirv/dbt-datamocktool/pull/58

br Petter
