### ISSUE TITLE
Unable to contribute

### ISSUE THREAD

**Issue by b0lle** [mjirv/dbt-datamocktool#47]
Hey, I would like to contribute a small section in the docs but I am not allowed to create a new branch. Can you please change your security policies?

Error was:
```
ERROR: Permission to mjirv/dbt-datamocktool.git denied to b0lle.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Thanks

**Comment by mjirv** [comment]
Can you create a fork instead and make a PR from that?

I'll look into the options around branches though too.

**Comment by pettersoderlund** [comment]
Suggest to close :)
